In [1]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
# importing dataset
dataset = pd.read_csv("CKD.csv")
dataset.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes

In [3]:
# Categorical data handling
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
# Dataset columns
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [6]:
# Feature and target selection
independent = dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent = dataset['classification_yes']

In [7]:
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [8]:
dependent

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int64

In [9]:
# Splitting data into training and testing sets
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.25,random_state=0)

In [10]:
x_train.shape

(299, 27)

In [11]:
x_test.shape

(100, 27)

In [12]:
y_train.shape

(299,)

In [13]:
y_test.shape

(100,)

In [14]:
# Data standardization
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [15]:
# GridSearch 
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV

# Defining the different parameters for gridsearch optimization
param_grid = {'var_smoothing': np.logspace(0, -9, num=100)}

grid = GridSearchCV(GaussianNB(),param_grid,refit=True,verbose=3,scoring='f1_weighted',n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 100 candidates, totalling 500 fits

GridSearchCV(estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             scoring='f1_weighted', verbose=3)

In [16]:
# Best gridseach parameter
grid.best_params_

{'var_smoothing': np.float64(0.005336699231206307)}

In [17]:
# Model prediction
y_pred = grid.predict(x_test)
y_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [18]:
# Evaluation metrics
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[36  0]
 [ 1 63]]

In [19]:
# Classification report
from sklearn.metrics import classification_report
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.97      1.00      0.99        36
           1       1.00      0.98      0.99        64

    accuracy                           0.99       100
   macro avg       0.99      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100

In [20]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

np.float64(1.0)

In [21]:
# Grid results
table = pd.DataFrame(grid.cv_results_)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_var_smoothing,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004058,0.000668,0.004343,0.000541,1.000000e+00,{'var_smoothing': 1.0},0.730960,0.801335,0.748958,0.801335,0.899920,0.796502,0.058819,100
1,0.003586,0.001753,0.004748,0.002171,8.111308e-01,{'var_smoothing': 0.8111308307896871},0.730960,0.818351,0.784116,0.818351,0.916508,0.813657,0.060554,99
2,0.002398,0.000701,0.003447,0.000311,6.579332e-01,{'var_smoothing': 0.657933224657568},0.748958,0.851888,0.801335,0.851888,0.933091,0.837432,0.061154,98
3,0.002351,0.000363,0.004241,0.001008,5.336699e-01,{'var_smoothing': 0.533669923120631},0.801335,0.868462,0.835193,0.851888,0.933091,0.857994,0.043627,97
4,0.002526,0.001298,0.003525,0.000921,4.328761e-01,{'var_smoothing': 0.43287612810830584},0.818351,0.901357,0.884943,0.901357,0.949701,0.891142,0.042367,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.001556,0.000047,0.002900,0.000116,2.310130e-09,{'var_smoothing': 2.310129700083158e-09},0.966898,1.000000,0.950189,1.000000,0.983123,0.980042,0.019339,63
96,0.002045,0.000623,0.005034,0.001637,1.873817e-09,{'var_smoothing': 1.873817422860387e-09},0.966898,1.000000,0.950189,1.000000,0.983123,0.980042,0.019339,63
97,0.002183,0.000677,0.003027,0.000167,1.519911e-09,{'var_smoothing': 1.519911082952933e-09},0.966898,1.000000,0.950189,1.000000,0.983123,0.980042,0.019339,63
98,0.001687,0.000092,0.003087,0.000276,1.232847e-09,{'var_smoothing': 1.2328467394420635e-09},0.966898,1.000000,0.950189,1.000000,0.983123,0.980042,0.019339,63
99,0.001628,0.000098,0.003288,0.000577,1.000000e-09,{'var_smoothing': 1e-09},0.966898,1.000000,0.950189,1.000000,0.983123,0.980042,0.019339,63

In [23]:
age_input=float(input("Enter age:"))
bp_input= float(input("Enter bp:"))
al_input=float(input("Enter al:"))
su_input=float(input("Enter su:"))
bgr_input=float(input("Enter bgr:"))
bu_input=float(input("Enter bu:"))
sc_input=float(input("Enter sc:"))
sod_input=float(input("Enter sod:"))
pot_input=float(input("Enter pot:")) 
hrmo_input=float(input("Enter hrmo:"))
pcv_input=float(input("Enter pcv:"))
wc_input=float(input("Enter wc:"))  
rc_input=float(input("Enter rc:"))  
sg_b_input=float(input("Enter sg_b:"))  
sg_c_input=float(input("Enter sg_c:"))  
sg_d_input=float(input("Enter sg_d:"))  
sg_e_input=float(input("Enter sg_e:"))  
rbc_normal_input=float(input("Enter rbc_normal:"))  
pc_normal_input=float(input("Enter pc_normal:")) 
pcc_present_input=float(input("Enter pcc_present:"))  
ba_present_input=float(input("Enter ba_present:"))  
htn_yes_input=float(input("Enter htn_yes:"))  
dm_yes_input=float(input("Enter dm_yes:"))  
cad_yes_input=float(input("Enter cad_yes:"))  
appet_yes_input=float(input("Enter appet_yes:"))  
pe_yes_input=float(input("Enter pe_yes:")) 
ane_yes_input=float(input("Enter ane_yes:"))

In [24]:
scaled_input = sc.transform([[age_input,bgr_input,al_input,su_input,bgr_input,bu_input,
                              sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,
                              rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,rbc_normal_input,
                              pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,
                              dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input]])

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [25]:
result = grid.predict(scaled_input)
result

array([1])