In [1]:
# Importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# Categorical data - One-Hot encodinng
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [7]:
# Training and testing data
X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [8]:
# Data standardization
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
scy = StandardScaler()
Y_train = scy.fit_transform(Y_train)
Y_test = scy.transform(Y_test)

In [10]:
# Model training
from sklearn.svm import SVR
regressor = SVR(kernel='poly',C=1000,gamma='scale')
regressor.fit(X_train,Y_train)

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1000, kernel='poly')

In [11]:
regressor.intercept_

array([-0.36612185])

In [12]:
regressor.n_support_

array([330], dtype=int32)

In [13]:
regressor.support_vectors_

array([[-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [-1.46169465,  0.27881295, -0.89833872, -0.97676557,  1.98149332],
       [ 0.10916367,  0.85484838, -0.06746417, -0.97676557, -0.50466988],
       ...,
       [-1.5330973 , -1.47416395, -0.89833872,  1.02378711,  1.98149332],
       [ 0.18056632,  0.83719827,  0.76341038,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(330, 5))

In [14]:
# Model prediction
Y_pred = regressor.predict(X_test)
Y_pred

array([-2.17561723e-01, -3.23303433e-01,  2.87684664e+00,  1.38727432e-02,
       -9.81068886e-02, -6.60442214e-01, -1.03085129e+00, -9.25198043e-02,
       -4.30366650e-01, -6.08837395e-01, -4.68341712e-01, -2.26452392e-01,
       -4.08843128e-01, -6.28051920e-01,  1.00116914e+00, -1.75835138e-01,
       -7.48640521e-02, -7.82035020e-01, -5.06335405e-01,  1.04461587e+00,
        1.06120880e+00, -3.30231896e-02, -2.47264298e-01,  1.43049177e+00,
       -8.95354698e-01, -6.43795157e-01, -5.63654143e-01, -3.71295307e-01,
       -6.89202385e-01, -3.39642422e-01, -3.93884520e-01,  3.34517355e+00,
        4.59940188e-02, -1.81260212e-01, -7.03924475e-02, -7.22868460e-01,
       -3.11521471e-01,  2.00265078e+00,  2.01824632e+00, -9.32960125e-01,
       -4.61169362e-01, -8.08095988e-01,  1.07190413e+00,  2.78967577e+00,
        1.91921484e+00, -8.43903306e-01, -1.77682413e-01, -4.65257930e-01,
       -6.51365396e-01, -1.01560485e-01, -8.51668322e-01, -8.95067998e-01,
        1.47818061e+00,  2.71082789e+00, -2.59911015e-02, -7.73002572e-01,
       -8.07533607e-01, -3.39245188e-01, -2.52238566e-01, -5.30697326e-03,
       -1.02527231e+00,  2.07358027e+00,  1.51669724e-01, -2.06810765e-01,
       -1.62087784e-01, -1.84669511e-01,  9.45862354e-01,  1.83538094e+00,
       -8.85833455e-01, -3.64221368e-01, -4.80680838e-02, -8.83517621e-02,
        5.73744399e-01,  1.01937832e-01, -6.75604613e-02, -7.44738062e-02,
       -3.96312578e-01, -3.63047604e-01,  9.65952756e-01,  2.87696876e+00,
       -1.63403543e-01,  3.50337391e+00, -9.16476968e-01, -3.92008878e-01,
        2.25480498e+00,  7.78610628e-01, -7.44423579e-01, -8.48739455e-01,
       -3.23349418e-02,  1.97755958e+00, -5.29054520e-01, -2.10985201e-01,
       -7.86233918e-01, -3.33119993e-01, -6.69384122e-01, -6.40932220e-01,
        2.05320782e+00,  1.65760857e+00, -6.18206325e-01, -1.54987910e-01,
       -8.91508464e-01, -5.76809444e-01, -6.82299961e-01,  2.05284684e+00,
        1.36763854e+00, -7.27005411e-01, -1.56364173e-01, -7.45929405e-01,
       -9.92232211e-02,  2.47027982e+00, -9.00641049e-02, -7.15378895e-01,
       -3.02499522e-01,  1.10671421e+00,  3.37146141e+00, -4.19388287e-01,
       -9.97122120e-01, -3.39817576e-01,  1.84219236e-02, -2.80384379e-01,
        2.27719379e+00, -9.17810669e-02,  1.67150705e-01, -6.08776829e-01,
       -3.88580131e-01, -6.35889739e-01,  1.17760738e+00,  6.89298266e-01,
        3.36311318e+00, -8.76179429e-01, -3.49168379e-01, -9.20550567e-01,
       -5.14367747e-01, -2.81725940e-01,  1.64536194e+00,  1.53261265e+00,
        8.97970461e-01, -2.17519147e-01,  7.40956093e-01, -8.96388416e-01,
       -9.45751479e-01, -2.15766290e-01, -2.30467534e-01, -2.25729789e-01,
       -6.46659019e-01,  1.22663939e-01,  2.86079652e-02, -8.36693025e-01,
       -1.06326286e+00, -1.70692885e-01, -5.16084545e-01,  2.58153288e+00,
       -2.35914037e-01, -9.79635258e-01, -8.69882641e-01, -4.73468128e-01,
       -8.74817292e-01, -9.89769592e-01, -1.76066424e-01, -2.06328739e-01,
       -6.81032404e-01,  5.12128251e-02, -7.57016882e-02, -2.35275174e-01,
       -5.75150188e-01, -6.89336672e-01, -8.69972999e-02, -5.82703733e-01,
       -7.14629005e-01, -9.19287049e-01, -7.15131888e-01, -7.42164127e-01,
       -3.67429383e-01, -8.37406642e-01, -7.00037231e-01, -6.69738142e-01,
       -7.48780723e-01, -5.04211483e-01,  1.87665207e+00, -1.07884181e+00,
       -1.54382882e-01, -4.79496690e-01, -1.34103769e-01, -8.05225438e-01,
       -5.96904178e-01,  1.61464327e+00, -9.21312945e-01, -9.22931835e-01,
        8.04238644e-02, -2.15371370e-01,  2.09087356e+00, -7.48600756e-01,
       -5.54339604e-01,  1.00174016e+00, -8.22767010e-01, -9.30556630e-01,
       -5.26454559e-01, -5.09480031e-01, -6.59117872e-01, -7.07959381e-01,
       -1.46216524e-01,  2.72533758e+00, -6.97638191e-02,  8.09664656e-01,
       -6.86061881e-01,  2.60410972e+00, -8.24592897e-01, -2.73879238e-01,
       -5.18797221e-01, -8.85380797e-01, -3.12813854e-01,  7.94209192e-03,
       -6.72964816e-01, -8.63120185e-01, -4.87425794e-01, -9.30997653e-01,
       -5.16400720e-01, -5.81463943e-01,  3.46268934e-02, -3.59439882e-01,
       -4.87600428e-01, -4.13631663e-01, -3.39176446e-01, -8.15671825e-01,
       -8.54387004e-02,  1.21732554e-01, -2.63601155e-03, -1.16949338e-01,
       -4.56849401e-01, -9.06668730e-01, -1.02757124e+00, -3.63855555e-01,
       -3.74027618e-02, -8.09393986e-01, -6.26763609e-01, -4.27932768e-01,
       -3.03343705e-01,  1.24445931e+00, -5.56058536e-01, -1.56901074e-01,
       -5.45878815e-01,  1.66042070e+00, -3.86185658e-01, -4.22506613e-01,
       -3.43601559e-01, -1.86913722e-01, -9.21409207e-01, -3.91276671e-01,
       -8.96064731e-01, -4.78200149e-01,  1.21508396e+00,  2.20287483e+00,
       -7.17907344e-01, -7.60652905e-01, -1.01958966e+00, -1.09516100e+00,
       -3.81248996e-01, -9.42545920e-01, -7.33823953e-01, -7.46190538e-01,
       -2.75219074e-01,  1.42068314e+00,  2.40905063e+00,  9.29980499e-02,
       -4.88128041e-01, -1.23022388e-01,  2.57441332e+00, -2.79859665e-01,
        1.95734455e+00, -9.58710696e-01,  2.11600806e+00, -6.07566056e-01,
       -4.24543423e-02, -7.87797972e-01,  2.09855626e+00, -5.90444384e-01,
       -2.58746415e-01, -2.04698879e-01, -9.01626744e-01, -2.55595902e-02,
       -1.20996903e-01, -6.64464639e-01, -7.05667640e-02, -1.01234586e+00,
       -5.30446142e-01, -7.60186523e-01, -2.20667428e-01,  1.01140751e+00,
       -8.36902125e-01, -1.08448655e+00, -9.96545143e-01,  2.80026000e+00,
       -2.97971257e-01, -6.57307617e-01, -6.26140652e-02, -1.20365010e-01,
        1.39790963e+00, -4.73442802e-01, -6.12970872e-01, -3.20122314e-01,
       -9.98980851e-01, -8.79323850e-01, -3.37684026e-01,  6.03672569e-01,
       -1.06569836e-02, -9.05227496e-01, -7.92613102e-01, -3.02847091e-01,
       -2.77206735e-01, -1.32099442e-01,  1.17034329e+00, -5.10366972e-01,
        5.08429744e-02, -9.83027325e-01, -5.67333057e-01, -6.71687952e-01,
       -3.32519801e-01, -1.02812022e+00, -5.00089760e-01,  2.85401620e+00,
       -8.02985266e-01, -7.46458812e-01, -9.78395056e-01, -3.27197102e-01,
       -7.21303861e-01, -9.46613476e-02,  2.47746638e+00,  3.55684025e-01,
       -2.91025201e-01,  2.52586361e+00, -6.65226488e-04, -6.83237845e-01,
       -2.44350656e-01, -7.29727193e-01,  1.76218002e+00, -6.47608243e-01,
       -2.53146589e-02, -1.01909207e+00,  3.30111516e-01, -7.69304042e-01,
        1.14100216e+00, -5.19212064e-01, -9.31735980e-01,  2.67411723e+00,
       -6.02397137e-01, -5.80512514e-01,  1.86182491e+00, -1.00177071e+00,
       -3.52049063e-01, -9.55815743e-01, -7.26669888e-03, -7.13245915e-01,
       -6.09648221e-01, -6.26639115e-01,  2.46747694e+00, -2.89298756e-01,
        1.54931297e+00,  1.94363410e+00, -5.55606539e-01, -2.85621601e-01,
       -1.03586792e+00, -7.70854500e-01, -9.15298754e-01, -3.04485713e-01,
        2.37522682e+00, -1.49506634e-01, -9.97703046e-01, -1.03749589e-01,
       -8.88027770e-01, -3.94832076e-01, -7.49212545e-01, -8.27035219e-01,
       -8.13062188e-01,  1.79816450e+00, -3.95835150e-01, -9.82951398e-01,
        2.32989796e+00, -1.23862833e-01,  2.28241643e+00, -1.20182624e-01,
       -6.55983881e-01, -9.04599793e-01, -9.67053157e-01, -2.03361521e-01,
       -6.24324817e-01, -9.95390119e-01, -2.04864132e-01, -4.40083526e-01,
       -5.25336782e-01, -7.52058324e-01, -8.92027409e-01,  2.16621219e+00,
       -9.47703314e-01, -2.85205006e-01, -9.30623867e-01, -4.14219180e-01,
       -1.52383009e-01, -7.13566174e-01,  5.71588002e-01, -1.80770526e-01,
        2.04803722e-01, -2.95836802e-02])

In [15]:
# Model evaluation
R2_score = r2_score(Y_test,Y_pred)
R2_score

0.8689312974410522

In [16]:
# User inputs
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

In [17]:
scaled_user_input = sc.transform([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]])
scaled_user_input

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[-1.31888935, -1.40436578, -0.06746417, -0.97676557, -0.50466988]])

In [18]:
result = regressor.predict(scaled_user_input)
result

array([-0.90097884])

In [20]:
scaled_Output = scy.inverse_transform([result])
scaled_Output

array([[2534.9078319]])

In [22]:
import pickle
filename = "SVR_PreProcessed_Input_Output_Saved_Model.sav"
pickle.dump(regressor,open(filename,'wb'))