In [1]:
# Importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# Categorical data - One-Hot encodinng
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [7]:
# Training and testing data
X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [8]:
# Data standardization
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
# Model training
from sklearn.svm import SVR
regressor = SVR(kernel='poly',C=1000,gamma='scale')
regressor.fit(X_train,Y_train)

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1000, kernel='poly')

In [10]:
regressor.intercept_

array([8490.93091261])

In [11]:
regressor.n_support_

array([936], dtype=int32)

In [12]:
regressor.support_vectors_

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(936, 5))

In [13]:
# Model prediction
Y_pred = regressor.predict(X_test)
Y_pred

array([ 9756.06434439,  8688.07479105, 46160.83353494, 12559.40867195,
        9921.79201961,  5020.65456315,  1175.83307363, 11081.1117749 ,
        7625.47014067,  5909.98150955,  6492.94821031,  9782.04303026,
        7841.57010896,  5059.5864424 , 23999.45993102, 10552.3917588 ,
       12430.20905461,  4304.51670178,  6967.09325025, 23344.8352343 ,
       24670.62627911, 11897.7816676 ,  9703.21125037, 28080.24696809,
        2333.95010807,  5666.43538823,  3952.18123513,  8195.05879593,
        4693.80628115,  8439.69377855,  7990.4585063 , 50047.90223738,
       13033.56992824, 10332.21722754, 13876.37698027,  4606.44510998,
        8876.61667699, 34335.3318196 , 32755.01238611,  2262.41028938,
        5707.8858269 ,  4077.46495547, 25070.31953113, 43591.90709127,
       31986.60524998,  3547.42467254, 10545.50792514,  7245.18156649,
        4892.92615155, 11751.95765723,  3242.83717759,  2647.30757578,
       28438.55753139, 41330.09459007, 11780.73973282,  4000.27818693,
        3479.72667768,  8744.3057861 , 10443.37543587, 12611.66041318,
        1257.70521849, 37260.55124912, 13952.69432562,  9716.17748923,
       10832.87654564, 10028.46016068, 22153.14928113, 32511.37544106,
        2934.42828118,  8484.72151116, 13083.18879629, 11329.97930554,
       18872.16408185, 14000.75986074, 12828.9390407 , 12639.95687141,
        7731.0450402 ,  8236.00308694, 22813.86510423, 43436.1896463 ,
       10991.94775792, 53189.48921572,  2331.46068795,  8040.13390155,
       37255.21842788, 21175.80992014,  4481.71777032,  3454.82138669,
       12107.41569454, 34569.59725313,  6516.61376672, 10314.28866892,
        3639.19303729,  8547.21037346,  5370.73937982,  5857.62668587,
       34566.54180592, 30518.52058296,  6021.11415721, 10549.28399406,
        2642.46746505,  6446.90705336,  5387.22998193, 35484.60812256,
       28105.77454367,  3605.5658512 , 10910.14690305,  4552.09679675,
       11414.99967605, 38847.05665753, 12111.46910827,  4801.85765627,
        8907.49925445, 23454.66580255, 50951.41337225,  7576.4177721 ,
        2162.1438156 ,  8744.58641989, 12196.8528765 ,  8967.53837065,
       38910.71077542, 10228.43928013, 14446.61456401,  5735.90704867,
        7926.4769878 ,  4961.9889463 , 24983.22181899, 20863.21105301,
       49418.93812644,  1895.19649001,  8420.84593068,  1916.78829591,
        6926.20461046,  9139.22446472, 30798.15251644, 29757.95398207,
       23370.4782338 ,  9794.30145066, 21593.88601048,  3300.12593973,
        2202.48083989, 10312.16515917,  9590.45727452, 10014.74249992,
        5651.98677202, 14496.96857613, 12580.92354305,  3557.17922036,
        1028.62515927, 10280.32626038,  6709.89568888, 42272.93365323,
        9552.181592  ,  1868.58093344,  2609.20214604,  7245.47434233,
        3196.54059132,  1845.18371274, 10551.5163658 ,  9896.42035986,
        5001.1713378 , 12925.40332319, 12707.41510758,  9595.85061426,
        4790.2162097 ,  4169.11843923, 13129.71619078,  6106.02432608,
        5143.05522086,  1441.87211014,  4906.90778931,  4827.3576476 ,
        8255.49365374,  2900.67201771,  4914.97497294,  4494.83600528,
        4579.45877318,  6535.52662109, 34824.27902752,   808.33430898,
       10531.58130008,  7198.97292061, 11044.68603524,  3758.14318668,
        5836.41182879, 30608.62982734,  2326.44715548,  2903.95028623,
       14504.59687905,  9774.06454413, 35153.36126941,  4743.41362702,
        6253.37546632, 24333.34331466,  3197.65750857,  2714.77981125,
        6811.59408874,  6748.67905233,  5367.05547425,  5239.46551088,
       10713.9540528 , 41560.04167834, 11519.91177312, 21338.90318961,
        5316.75908181, 39514.88099054,  3996.75896508,  9421.46830952,
        6943.27882425,  -157.26116349,  8800.04600371, 13515.92677264,
        5167.84086656,  3194.05882934,  7162.1227214 ,  2630.25312187,
        6794.52699749,  5524.90859193, 13942.90755402,  6865.21909457,
        6959.36984804,  7590.22087126,  8528.89247606,  3150.70654878,
       11806.44656264, 13964.28060086, 11974.29223294, 11857.14603367,
        6964.13154915,  2986.69633395,   934.17492695,  8405.79313457,
       12234.88596008,  2258.96104323,  5364.04583816,  7707.121269  ,
        8851.90673822, 26069.77595654,  6550.83320657, 10744.71488851,
        6241.38303707, 28094.36354392,  8133.35611282,  7219.63340639,
        8459.25782132, 10077.01609974,  2950.389562  ,  8103.64282877,
        2296.08909697,  6967.182501  , 24955.84715174, 35939.01367075,
        4965.54009646,  4242.37005011,  1360.56690604,   702.01066142,
        8183.91662941,  1594.15872522,  4296.82362752,  4267.02842334,
        8661.66098296, 27311.48310491, 38224.74669495, 14326.79054985,
        7142.28795691, 10899.34923555, 38456.10692623,  8936.45244387,
       35742.99635576,   923.09641089, 32625.39205081,  6051.39141054,
       12105.92447462,  4288.70697707, 35687.69264803,  6345.93361884,
        9682.5958052 , 11116.13006792,  2602.34404281, 12878.56750784,
       11785.98639841,  5367.02119822, 12239.7278895 ,  1418.2661428 ,
        6857.42117716,  3885.16953849,  9813.36154961, 23359.48274424,
        2735.11823257,   783.86866499,  2078.64932109, 41309.09141151,
        8822.22126862,  5731.81579937, 11544.29097331, 11039.33256117,
       27387.15878527,  7103.1022354 ,  6121.35344711,  8874.64105501,
        1306.82888963,  2908.05373251, 10000.80775244, 20144.00947915,
       13527.52281198,  3006.03549031,  4374.94065546,  8792.76231245,
        9411.66793814, 12575.27600906, 25878.96841151,  6703.18744532,
       14483.27880854,  1790.28034541,  6302.30291488,  5367.60782751,
        8199.18464804,  1787.92865459,  6992.33529894, 43380.08240562,
        3901.66824082,  4861.23001175,  1312.46464127,  8712.68598207,
        4809.29276756, 12034.44335237, 38209.26313895, 16839.947078  ,
        9004.17363974, 41320.28184705, 12271.70469689,  5332.58613135,
        9472.33840686,  3797.97783722, 31744.99376956,  5723.25307395,
       13532.50917923,  1956.36651246, 16958.52902364,  3367.63292766,
       26959.23263132,  6829.31274254,  2637.79519624, 41009.32611344,
        5895.8945619 ,  5764.49876767, 33864.02867217,  1303.05545353,
        8309.63022591,  2410.09793669, 13373.34075722,  3948.02605189,
        6098.86114766,  5702.30656274, 39129.78682592,  8509.72869542,
       28393.23379506, 32822.44014886,  6563.80890092,  9900.62435616,
        1228.61835427,  3688.95813971,  2818.67821944,  8903.58978873,
       38569.02639295, 11186.4832139 ,  1422.47660293, 11960.41636748,
        2643.9723426 ,  8000.12174375,  4842.08310513,  1966.57405983,
        4166.84591323, 30928.36832773,  6755.16360217,   908.49359965,
       38601.95350397, 10738.06172558, 37599.017519  , 11625.62270576,
        5670.08272017,  2313.69010469,  2029.08276733,  9959.74841297,
        5936.59807248,  1513.47591281, 10053.2208494 ,  7513.54616945,
        6791.83135144,  4706.13862796,  2881.76651808, 36510.78204666,
        1999.87022678,  9022.84323861,  1549.55657766,  7964.13457554,
       10587.97389119,  4781.91414116, 17049.91915332, 10307.4119069 ,
       14314.97818497, 13732.18919608])

In [14]:
# Model evaluation
R2_score = r2_score(Y_test,Y_pred)
R2_score

0.8566487675946548

In [15]:
# User inputs
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

In [16]:
scaled_user_input = sc.transform([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
scaled_user_input

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([[-1.31888935, -1.08345468, -0.06746417, -0.97676557, -0.50466988]])

In [17]:
result = regressor.predict(scaled_user_input)
result

array([2749.06685487])

In [20]:
import pickle
filename = "SVR_PreProcessed_Input_Saved_Model.sav"
pickle.dump(regressor,open(filename,'wb'))
pickle.dump(sc,open("X_Scaler.pkl",'wb'))