In [1]:
# Importing necssary libraries
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# Categorical data - One-Hot encodinng
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [7]:
# Training and testing data
X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [8]:
X_train.shape

(936, 5)

In [9]:
X_test.shape

(402, 5)

In [10]:
Y_train.shape

(936, 1)

In [11]:
Y_test.shape

(402, 1)

In [24]:
# Model training
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=100, 
                                  criterion='squared_error', 
                                  max_features='log2')
regressor.fit(X_train,Y_train)

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(max_features='log2')

In [25]:
Y_pred = regressor.predict(X_test)
Y_pred

array([10437.0690934 ,  9125.1450514 , 44486.0490621 , 13463.453634  ,
        9649.5206744 , 11339.4770357 ,  1988.290838  , 12222.1319084 ,
        7449.2415247 ,  6619.7114475 ,  6304.3744948 , 13457.5908746 ,
        7862.6416279 ,  6091.6256401 , 22489.5646042 , 12263.324005  ,
       13838.9286704 ,  3863.352893  ,  6990.2823343 , 31003.8376201 ,
       24384.6524287 , 17514.1365267 , 10616.1843071 , 27165.3581849 ,
        2748.3420734 ,  7050.60677   ,  3722.8177295 ,  8092.5584958 ,
        3740.0154695 , 10664.7343533 ,  8230.099785  , 44611.3130808 ,
       14430.6427152 , 14717.812707  , 18377.2333929 ,  4931.3413415 ,
        9599.4589966 , 37509.9638565 , 37592.44685   ,  2133.242837  ,
        5914.2308249 ,  3907.3419334 , 20771.2056027 , 46010.5999982 ,
       36164.643917  ,  3389.1737382 , 12197.6607355 ,  6786.5630752 ,
        6234.8321819 , 14242.5260453 ,  4062.8303674 ,  4432.126201  ,
       27077.3624346 , 46121.6534055 , 11518.8897615 , 10254.3711992 ,
        4161.8516768 , 11190.4942063 ,  9143.3306038 , 15909.8431332 ,
        2120.5299609 , 44032.0518811 , 15853.1107013 , 18150.3729988 ,
       11441.599122  , 10219.3579118 , 29565.7256289 , 39299.5024514 ,
        4443.4128141 , 10065.7823059 , 15418.9389627 , 11511.3323522 ,
       17437.5114141 , 14499.350257  , 13643.0260763 , 13591.8307827 ,
        9579.5873161 , 14867.4226659 , 21377.4798099 , 44388.4923673 ,
       11544.842051  , 47398.8480726 ,  3901.5080548 ,  9446.7757129 ,
       40064.2099734 , 19681.1212775 ,  5545.4390375 ,  3542.1802771 ,
       12731.3874827 , 38083.2906464 ,  6136.1517621 , 14621.0455822 ,
        4501.6544149 ,  9678.5990585 , 10389.4164021 ,  4556.5654114 ,
       41996.1959977 , 40338.3149136 ,  5598.9524939 , 11233.7398839 ,
        3592.8355777 ,  7598.7846581 ,  7402.1623499 , 37589.5296739 ,
       25542.9414829 ,  3886.0944174 , 10988.9759425 ,  4701.8404024 ,
       11778.1961832 , 44135.2422109 , 11621.390529  ,  8368.9497329 ,
       10043.8519004 , 33941.8043016 , 44361.9337415 ,  8155.097899  ,
        2926.9576115 , 10583.0343333 , 16368.3528464 ,  9710.3928675 ,
       42355.9556781 , 11668.6241855 , 14459.2767675 ,  8451.3408649 ,
       11642.6567655 ,  5633.0790885 , 24736.4779751 , 25073.6660058 ,
       46017.587309  ,  1575.229109  , 12670.1054239 ,  3224.9874678 ,
        8068.2694709 ,  9146.5397659 , 32249.1084883 , 32837.1480675 ,
       26123.0500284 , 11454.1725088 , 24572.479576  ,  6454.8839034 ,
        2226.2530447 , 12539.6433708 , 11322.330493  , 11445.6789988 ,
        6588.1639922 , 14524.0979435 , 20740.5300804 , 13040.5386747 ,
        2003.4761636 , 11264.6425435 ,  6968.9358722 , 38626.3561085 ,
        9854.7476922 ,  6391.9519488 ,  3627.7738619 ,  7542.3934244 ,
        3150.4942926 ,  6011.0732442 , 12263.324005  ,  9918.2603321 ,
        6201.4767487 , 12982.2315685 , 13390.1828271 ,  9250.2313705 ,
        4083.7534601 ,  8217.8767843 , 16896.8519571 ,  8755.458589  ,
        5511.663967  ,  2130.048465  ,  7231.6851113 ,  6060.4343411 ,
       10918.9012934 ,  2913.7969427 ,  7534.292631  ,  8524.0221982 ,
        4858.7960803 ,  6455.6000002 , 32617.7258393 ,  2062.2316853 ,
       15050.2996412 ,  7123.4274123 , 11319.1176307 ,  5947.3324408 ,
        8374.4998357 , 27940.3609499 ,  3908.0825309 ,  3221.1032972 ,
       14258.752073  , 11133.4914398 , 42112.5969622 ,  6323.0044843 ,
        5455.7436885 , 27474.9800099 ,  3447.5972599 ,  3002.613635  ,
        8836.6077716 ,  7236.7589487 ,  9439.1622427 ,  4733.7777818 ,
       12448.1524415 , 44681.0872969 , 17860.2929161 , 19754.4570324 ,
       12950.8075729 , 42708.0415271 ,  4157.6451695 , 10024.0463608 ,
        9543.7050246 ,  3001.0660565 ,  9741.4511939 , 13799.1456479 ,
        7426.9805529 ,  5007.812384  ,  6641.0466036 ,  6565.3117199 ,
        6680.9896445 ,  7139.6658866 , 13670.7877545 ,  7062.4503908 ,
       10475.4619418 ,  8306.4510173 , 11114.6947767 , 12003.805489  ,
       12523.6694984 , 14539.1605051 , 18357.3759895 , 13298.0252843 ,
        6734.3511994 ,  2945.3478867 ,  6146.339106  ,  7970.780426  ,
       14217.2389434 ,  7261.2316249 ,  6473.6357505 ,  7203.6121373 ,
       12895.2245058 , 32411.1360933 ,  6030.2109252 , 11876.4899944 ,
        7754.9044022 , 37200.5870475 ,  9637.6582286 ,  8154.4203367 ,
       11835.467688  , 10565.7268569 ,  3371.6673688 ,  7967.2931082 ,
        5027.0280598 ,  6277.887554  , 19258.903111  , 43671.5530672 ,
        5830.031491  ,  5645.8136074 ,  6589.3116104 ,  1665.057647  ,
        8551.7904195 ,  3515.86101142,  6206.0807055 ,  8880.1284588 ,
        8341.9934575 , 25770.7764963 , 43885.9210499 , 15926.0213883 ,
        6405.016959  , 11013.898882  , 42686.6490076 ,  9807.4940959 ,
       39698.829081  ,  1404.526964  , 38117.053522  ,  5414.6658705 ,
       12664.5748638 ,  7327.1637501 , 39353.7267916 ,  5568.697859  ,
       10519.4165083 ,  9294.2638473 ,  3661.3940913 , 15702.0066747 ,
       11937.5667288 , 11737.7694957 , 14892.634314  , 14235.1333015 ,
        8087.8677695 ,  5655.505434  ,  9795.1844295 , 22647.5187772 ,
        4852.8399813 ,  1754.9153684 ,  2787.0727679 , 45825.0406355 ,
       12488.4898032 ,  4989.5657992 , 17433.500554  , 13314.4297572 ,
       34207.2960558 ,  8004.5962121 ,  5703.7920683 ,  9520.3256378 ,
        3556.3348779 ,  4879.7106061 , 21887.8486055 , 17791.5192244 ,
       13362.9458126 ,  2923.6499122 ,  3955.0868431 ,  9463.5739555 ,
       10500.5774743 , 17091.7844798 , 20849.803843  ,  8473.5421835 ,
       17729.0001598 ,  2594.364705  ,  8586.3305918 ,  9749.2884064 ,
       14574.3214616 ,  3290.4345382 ,  8117.3348186 , 45209.1900548 ,
        4134.6764177 ,  5857.2529994 ,  2200.1209479 , 13561.8171721 ,
        5314.7557595 , 11867.798096  , 43362.2709952 , 19088.5141979 ,
        9928.3787047 , 42636.8782638 , 16311.1974719 , 11764.5732668 ,
       10253.2981413 ,  6380.4678737 , 28807.9679565 ,  5006.5543429 ,
       14093.6471017 ,  2588.5250016 , 17523.4050224 ,  3375.1844899 ,
       27254.8685265 ,  8328.3015248 ,  5108.6194281 , 39443.0895314 ,
        7500.0382481 ,  5218.482864  , 32625.1267922 ,  3703.8627279 ,
        8704.3362427 ,  4165.2059281 , 12759.3895202 ,  3970.0210292 ,
        8492.7508668 ,  7746.5063658 , 44663.9389333 , 10668.4301654 ,
       32008.3040378 , 38578.5747479 ,  6114.5547206 ,  9630.6015885 ,
        1685.9852101 ,  4752.394968  ,  4190.6163495 ,  9814.0899133 ,
       46144.3843099 , 11487.662069  ,  2264.1017313 , 13256.911786  ,
        2633.845161  , 14199.4099306 , 10264.8932897 ,  2610.8493003 ,
        3893.4274759 , 36047.125494  ,  6503.3080968 ,  2032.726825  ,
       39938.3181768 , 11886.8538285 , 44388.3083097 , 11458.0541956 ,
        7537.9447054 ,  3654.9683256 ,  2141.800521  , 12482.5595062 ,
        6595.0222455 ,  2464.4163272 , 10406.3062903 ,  7124.9042065 ,
        7562.4108518 ,  7310.119196  ,  9219.6477936 , 41439.2938535 ,
        4175.2384257 , 15870.737499  ,  6771.43146753, 17042.7544045 ,
       11289.0357189 ,  7252.1150781 , 18095.4466031 , 13557.0713816 ,
       18725.3842194 , 19127.1846545 ])

In [26]:
# Model evaluation
from sklearn.metrics import r2_score
score = r2_score(Y_test,Y_pred)
score

0.8713941702513055

In [32]:
# Saving the model
import pickle 
filename = "Regression_Assignment_Best_Model"
pickle.dump(regressor,open(filename,'wb'))

In [33]:
result = regressor.predict([[19,27.87,0,1,0]])
result

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([1690.5834101])