In [1]:
# Importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# Categorical data - One-Hot encodinng
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [7]:
# Training and testing data
X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [21]:
# Data standardization
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [166]:
# Model training
from sklearn.svm import SVR
regressor = SVR(kernel='sigmoid',C=1000)
regressor.fit(X_train,Y_train)

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1000, kernel='sigmoid')

In [167]:
regressor.intercept_

array([11595.56286782])

In [168]:
regressor.n_support_

array([936], dtype=int32)

In [169]:
regressor.support_vectors_

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]],
      shape=(936, 5))

In [170]:
# Model prediction
Y_pred = regressor.predict(X_test)
Y_pred

array([ 9.73127388e+03,  1.05418915e+04,  2.11994543e+04,  6.05434487e+03,
        6.19831318e+03,  9.85602870e+03, -8.32580852e+03,  1.55294744e+03,
        1.01406729e+04,  2.63623447e+03,  1.01438986e+04,  9.26308551e+03,
        9.14566124e+03, -5.44931785e+02,  2.46325008e+04,  7.38571328e+03,
        3.12761936e+03,  5.68501942e+03,  7.17919030e+03,  2.10237946e+04,
        3.61633683e+04,  6.63245234e+03,  1.67644853e+04,  3.01996292e+04,
        8.45906627e+03,  8.61324760e+03, -6.13966689e+03,  8.16827057e+03,
       -1.19714475e+03,  1.18268160e+04,  1.00821911e+04,  2.34868706e+04,
        5.50862941e+03,  5.54085499e+03,  2.59913078e+04, -9.50514397e+02,
        1.68929255e+04,  1.00647090e+04,  2.53150657e+04, -5.22809683e+03,
       -1.24889822e+03,  9.91701548e+03,  2.82087491e+04,  3.17854920e+04,
        1.42465299e+04,  8.33152786e+03,  7.59289666e+03,  6.94551924e+03,
        4.98138526e+02,  1.24854084e+04, -2.29826395e+03,  1.40915181e+04,
        2.94360521e+04,  1.18401832e+04,  2.07455746e+04,  7.30683810e+03,
        7.48177512e+03,  4.28882048e+03,  1.20241651e+04,  9.35727688e+03,
        1.20757010e+04,  4.58073650e+04,  2.56571679e+04,  1.55091181e+04,
        1.99771912e+04,  1.27263491e+04,  2.17562450e+04,  9.84818935e+03,
        5.08144193e+03,  1.04436388e+04,  2.09597127e+04,  1.00303040e+04,
        2.65312675e+04,  2.24188296e+04,  1.77989190e+04,  2.01259008e+04,
        5.67563710e+03,  1.13741102e+04,  3.16118727e+04,  2.83485597e+04,
        1.84096487e+04,  1.72738854e+04,  9.34215927e+03,  8.39454481e+03,
        1.88304956e+04,  2.22150500e+04,  9.32304761e+03,  9.17266760e+03,
        1.03251031e+04,  1.46513186e+04,  1.00547181e+04,  3.36005820e+03,
        4.55529297e+03,  8.92859449e+03,  6.68677817e+03,  5.27516626e+03,
        2.54854973e+04,  2.62571658e+04,  8.84573153e+03,  7.40649881e+03,
        8.94548401e+03,  7.94607093e+03,  8.83150204e+03,  1.66036291e+04,
        2.63511919e+04, -5.05601507e+03,  3.49140854e+03,  1.17109148e+03,
        4.30044336e+03,  2.47055357e+04,  9.71123320e+03,  1.39568683e+04,
        1.07935950e+04,  1.93524054e+04,  2.19484333e+04,  7.75195543e+03,
        6.16930907e+03,  4.26448295e+03,  1.37637347e+04,  1.20837079e+04,
        2.16973919e+04,  7.11952402e+03,  2.21426800e+04,  6.84674122e+03,
        8.75177951e+03,  5.08338511e+03,  3.19606008e+04,  3.21191422e+04,
        1.89406906e+04,  7.32084485e+03,  8.72277051e+03,  4.33757810e+03,
        7.39840962e+03,  4.39619035e+03,  2.36905607e+04,  2.14716817e+04,
        3.03796511e+04,  9.16852762e+03,  3.41884596e+04,  5.49420489e+03,
       -5.90672864e+03,  3.39461201e+03,  1.77927569e+04,  3.78903234e+03,
        6.05597782e+03,  2.28317822e+04,  1.34902693e+04,  5.85546488e+03,
        1.54865014e+04,  8.56274590e+03,  6.12566253e+03,  9.09380554e+03,
        1.03011596e+04,  4.70594933e+03,  4.89253820e+03,  7.91830603e+03,
        5.01978707e+03,  4.83551696e+03,  7.41112353e+03,  4.70051871e+03,
        5.02174385e+02,  6.99364211e+03,  1.91322118e+04,  1.40807260e+04,
       -3.00174587e+03, -3.17202863e+03,  2.46509002e+04,  1.21904521e+04,
        5.98497718e+03, -1.46449805e+03,  3.33528696e+03,  1.14194314e+03,
        8.62856846e+03,  7.50489337e+03, -9.44710929e+02, -2.30256700e+03,
        1.20718700e+01,  5.55186227e+03,  4.38983788e+04,  1.39501317e+04,
        7.86551871e+03,  7.53028871e+03,  4.00351629e+03,  7.88386429e+03,
        2.16835974e+03,  3.05134115e+04,  9.56189177e+03, -7.74767638e+02,
        2.31465013e+04,  7.61691621e+03,  2.29289987e+04,  8.21467963e+03,
        4.67561433e+03,  3.08358268e+04,  7.50527096e+03,  1.24372153e+04,
        6.92008557e+03,  9.85808688e+03,  7.39683806e+03,  6.06190149e+03,
        1.31037012e+04,  2.50164142e+04,  7.19108026e+03,  1.61275472e+04,
        3.57313593e+03,  1.99877559e+04, -5.05879693e+02,  4.28633435e+03,
        8.90477248e+03,  6.93704559e+03,  9.71014629e+03,  2.23327774e+04,
        1.30380669e+04, -3.21807938e+03,  7.35514234e+03,  1.33466600e+04,
        4.74186782e+03,  1.61199206e+03,  5.42016765e+03,  4.29763169e+03,
        9.00783647e+03,  1.11431271e+04,  1.31066128e+04, -5.45257563e+03,
        2.06750368e+04,  5.80622988e+03,  5.36367599e+03,  1.74930218e+04,
        2.78733621e+03,  1.21520733e+04,  1.12631659e+04,  1.31066406e+04,
        2.12125809e+04,  1.93422266e+04,  2.01575494e+03,  1.05602360e+04,
        1.03300483e+04,  2.04219650e+04,  6.78922606e+03,  9.56331626e+03,
        4.77869776e+03, -2.47881680e+02,  8.22941739e+03,  6.95826227e+03,
        1.22075295e+04,  1.02701355e+04, -1.71733481e+03,  1.02655888e+04,
       -6.88748018e+03,  6.27479587e+03,  2.89586177e+04,  2.09987061e+04,
        8.97368465e+03,  8.81983181e+03, -7.93579841e+03,  1.54528954e+04,
        9.71730035e+03, -4.12048385e+03, -5.83791958e+03,  9.43482895e+01,
        7.35629390e+03,  3.09449405e+04,  2.60772476e+04,  7.89818974e+03,
        7.26684342e+03,  7.35922139e+03,  2.04376899e+04,  1.14454000e+04,
        1.67383127e+04,  8.43221011e+03,  2.43001380e+04,  7.46022260e+03,
        1.40134231e+04,  7.36948248e+03,  1.47202023e+04,  6.72737646e+03,
        3.63641747e+03,  1.37321511e+04,  4.69286787e+03,  1.47013764e+04,
        1.87814671e+04,  6.69103110e+03,  3.14033806e+03, -7.70393246e+03,
        9.94288322e+03, -2.34244833e+03,  6.73751206e+03,  3.22413360e+04,
        1.28280283e+04,  1.43278353e+04, -2.37853408e+03,  2.13126974e+04,
        7.80710879e+03,  5.33069049e+03,  6.87028997e+03,  1.33454902e+04,
        1.97860763e+04,  7.03060714e+03,  6.81476347e+03,  5.23566016e+03,
        1.07828421e+04, -9.42349333e+02,  3.70217842e+04,  2.55494596e+04,
        2.20240055e+04,  1.19347329e+04,  2.76040449e+03,  1.23546301e+04,
        4.05284456e+03,  2.44522395e+04,  1.42327883e+04,  9.28317771e+03,
        2.46460022e+04, -7.03841245e+03,  8.64473835e+03,  6.71602455e+03,
        9.30957793e+03, -2.54431593e+03,  6.11680149e+03,  1.99810942e+04,
        8.86854236e+03,  3.62216096e+03, -8.11123600e+03,  1.50050528e+04,
        2.41895439e+03,  1.54684428e+04,  2.48683023e+04,  2.14969778e+04,
        9.54170407e+03,  1.85087770e+04,  6.30202125e+03,  3.78262115e+03,
        9.47397970e+03,  1.31856410e+03,  3.36201328e+04,  4.52725044e+03,
        1.66293237e+04,  5.89294193e+03,  2.38351740e+04, -5.29400794e+03,
        4.09874181e+04,  1.33926162e+04,  1.32706557e+04,  1.55074824e+04,
        1.23757631e+04,  2.51149776e+03,  2.13125018e+04,  1.09131992e+04,
        1.05710910e+04, -2.18078725e+03,  2.08758562e+03, -1.60794653e+03,
        1.41503273e+04,  2.15663656e+03,  2.11641330e+04,  8.76059592e+03,
        2.74585395e+04,  7.24136017e+03,  6.83143908e+03,  1.10447605e+04,
        1.26481775e+04, -4.23459655e+03,  7.59015057e+03,  1.18252015e+04,
        3.13535725e+04,  3.38067154e+03, -8.00024937e+03,  3.18203957e+03,
       -3.04184036e+03,  1.28668247e+04,  5.87021792e+03,  7.44755246e+03,
        5.56719873e+03,  1.19727232e+04,  7.84219553e+02, -8.48129301e+03,
        1.36692505e+04,  1.12397312e+04,  2.78450008e+04,  3.27924197e+03,
        7.12241570e+03,  1.41057363e+04, -6.90965377e+03,  8.05364350e+03,
        6.33034712e+03, -7.08873549e+03,  1.24980160e+04,  1.08693759e+04,
        6.22191903e+03,  8.10231027e+03, -5.41705285e+03,  8.48387984e+03,
        1.00141635e+04,  1.24501970e+04, -3.01223149e+03,  1.22052224e+04,
        6.92892258e+03,  7.44508161e+03,  4.57421461e+03,  6.11376005e+03,
        1.50605614e+04,  1.96845177e+04])

In [171]:
# Model evaluation
R2_score = r2_score(Y_test,Y_pred)
R2_score

0.28747069486976307